trigger:
- main

pool:
  name: devops-poc-SSA

stages:

# ✅ BUILD (NO ZIP)
- stage: Build
  jobs:
  - job: BuildWebsite
    steps:
    - checkout: self

    - publish: $(Build.SourcesDirectory)
      artifact: website

# ✅ DEPLOY TO TEST SLOT
- stage: Deploy_Test
  dependsOn: Build

  jobs:
  - deployment: DeployWeb
    environment: test-env

    pool:
      name: devops-poc-SSA

    strategy:
      runOnce:
        deploy:
          steps:

          - download: current
            artifact: website

          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'devops-poc'
              appName: 'poc-devops-webapp'
              slotName: 'test'
              package: $(Pipeline.Workspace)/website