trigger:
- main

pool:
  name: devops-poc-SSA

stages:

# ✅ BUILD WITH APPROVAL
- stage: Build
  jobs:
  - deployment: BuildJob
    environment: build-env   #  approval here

    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: $(Build.SourcesDirectory)
              includeRootFolder: false
              archiveType: zip
              archiveFile: $(Build.ArtifactStagingDirectory)/site.zip

          - publish: $(Build.ArtifactStagingDirectory)/site.zip
            artifact: website


# ✅ TEST DEPLOY (WITH APPROVAL)
- stage: Deploy_Test
  dependsOn: Build

  jobs:
  - deployment: DeployWeb
    environment: test-env

    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: website

          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'devops-poc'
              appName: 'devops-app'
              slotName: 'test'
              package: $(Pipeline.Workspace)/website/site.zip
              deploymentMethod: zipDeploy


# ✅ PROD DEPLOY (WITH APPROVAL)
- stage: Swap_To_Prod
  dependsOn: Deploy_Test

  jobs:
  - deployment: SwapSlots
    environment: prod-env

    strategy:
      runOnce:
        deploy:
          steps:

          - task: AzureAppServiceManage@0
            inputs:
              azureSubscription: 'devops-poc'
              Action: 'Swap Slots'
              WebAppName: 'devops-app'
              ResourceGroupName: 'rg-devops-poc'
              SourceSlot: 'test'