trigger:
- main

pool:
  name: devops-poc-SSA

stages:

# ---------------- BUILD (WITH APPROVAL) ----------------
- stage: Build
  jobs:
  - deployment: BuildJob
    timeoutInMinutes: 60
    environment: build-env

    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - script: |
              echo ===== BUILD STAGE =====
              echo Files:
              dir $(Build.SourcesDirectory)


# ---------------- DEPLOY TO TEST (WITH APPROVAL) ----------------
- stage: Deploy_Test
  dependsOn: Build

  jobs:
  - deployment: DeployWeb
    timeoutInMinutes: 60
    environment: test-env

    strategy:
      runOnce:
        deploy:
          steps:

          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'devops-poc'
              appName: 'devops-app'
              slotName: 'test'
              package: '$(Build.SourcesDirectory)'


# ---------------- SWAP TO PROD (WITH APPROVAL) ----------------
- stage: Swap_To_Prod
  dependsOn: Deploy_Test

  jobs:
  - deployment: SwapSlots
    timeoutInMinutes: 60
    environment: prod-env

    strategy:
      runOnce:
        deploy:
          steps:

          - task: AzureAppServiceManage@0
            inputs:
              azureSubscription: 'devops-poc'
              Action: 'Swap Slots'
              WebAppName: 'devops-app'
              ResourceGroupName: 'rg-devops-poc'
              SourceSlot: 'test'